// David Jones
// MIU 1305
// Week 3

var jsonObj = {
	"character1": {
		"cName": ["Name:", "Attricane"],
		"account": ["Account:", "Havok79"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Rapture"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2010-07-15"],
		"charClass": ["Class:", "Swashbuckler"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "320"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "Yes"],
		"skyshrine": ["Skyshrine:", "Yes"],
		"bio": ["Bio:", "Ubah Swash!"]
	},
	"character2": {
		"cName": ["Name:", "Trevail"],
		"account": ["Account:", "cohesivepanic79"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Rapture"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2009-07-15"],
		"charClass": ["Class:", "Fury"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "320"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "Yes"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Ubah Fury!"]
	},
	"character3": {
		"cName": ["Name:", "Attritank"],
		"account": ["Account:", "Havok1979"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Rapture"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2011-09-20"],
		"charClass": ["Class:", "Monk"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Ubah Monk!"]
	},
	"character4": {
		"cName": ["Name:", "Royale"],
		"account": ["Account:", "dljones79"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Rapture"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2011-09-20"],
		"charClass": ["Class:", "Dirge"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "317"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "Yes"],
		"bio": ["Bio:", "Ubah Dirge!"]
	},
	"character5": {
		"cName": ["Name:", "Vesuvious"],
		"account": ["Account:", "Havok79"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Rapture"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2011-09-20"],
		"charClass": ["Class:", "Berserker"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "92"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Ubah Zerk!"]
	},
	"character6": {
		"cName": ["Name:", "Blayne"],
		"account": ["Account:", "icemaner24"], 
		"server": ["Server:", "Freeport"],
		"guild": ["Guild:", "Darknessfalls"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2007-09-08"],
		"charClass": ["Class:", "Shadowknight"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "90"],
		"aa": ["AA\'s:", "280"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Gimp SK!"]
	},	
	"character7": {
		"cName": ["Name:", "Atun"],
		"account": ["Account:", "jesse08"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Bacon"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2010-06-20"],
		"charClass": ["Class:", "Illusionist"],
		"sex": ["Sex:", "Female"],
		"level": ["Level:", "92"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Ubah Illy!"]
	},	
	"character8": {
		"cName": ["Name:", "Brigade"],
		"account": ["Account:", "fifo2020"], 
		"server": ["Server:", "Everfrost"],
		"guild": ["Guild:", "Strike"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2009-04-20"],
		"charClass": ["Class:", "Guardian"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "80"],
		"aa": ["AA\'s:", "275"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Old Guardian."]
	},	
	"character9": {
		"cName": ["Name:", "Mezztress"],
		"account": ["Account:", "timsaccount"], 
		"server": ["Server:", "Freeport"],
		"guild": ["Guild:", "Darknessfalls"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2007-10-19"],
		"charClass": ["Class:", "Coercer"],
		"sex": ["Sex:", "Female"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "320"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "Yes"],
		"skyshrine": ["Skyshrine:", "Yes"],
		"bio": ["Bio:", "Darknessfalls guild leader."]
	},
	"character10": {
		"cName": ["Name:", "Paganini"],
		"account": ["Account:", "bryzan80"], 
		"server": ["Server:", "Unrest"],
		"guild": ["Guild:", "Symphony of the Night"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2009-01-11"],
		"charClass": ["Class:", "Troubadour"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "92"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Ubah Troub!"]
	},
	"character11": {
		"cName": ["Name:", "Attrikane"],
		"account": ["Account:", "Havok79"], 
		"server": ["Server:", "Everfrost"],
		"guild": ["Guild:", ""],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2011-09-20"],
		"charClass": ["Class:", "Ranger"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "90"],
		"aa": ["AA\'s:", "292"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Ranger in training."]
	},
	"character12": {
		"cName": ["Name:", "Kataklysm"],
		"account": ["Account:", "sancho251"], 
		"server": ["Server:", "Unrest"],
		"guild": ["Guild:", "Enrapture"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2008-07-20"],
		"charClass": ["Class:", "Warlock"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "320"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "Yes"],
		"skyshrine": ["Skyshrine:", "Yes"],
		"bio": ["Bio:", "Kyle's lock."]
	},
	"character13": {
		"cName": ["Name:", "Stratix"],
		"account": ["Account:", "b8seball88"], 
		"server": ["Server:", "Permafrost"],
		"guild": ["Guild:", "Bacon"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2013-01-20"],
		"charClass": ["Class:", "Dirge"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "320"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "Yes"],
		"skyshrine": ["Skyshrine:", "Yes"],
		"bio": ["Bio:", "Aaron's dirge."]
	},	
	"character14": {
		"cName": ["Name:", "Karthes"],
		"account": ["Account:", "karthes65"], 
		"server": ["Server:", "Freeport"],
		"guild": ["Guild:", "Black"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2012-06-22"],
		"charClass": ["Class:", "Templar"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "320"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "Yes"],
		"bio": ["Bio:", "Ubah Tempy!"]
	},	
	"character15": {
		"cName": ["Name:", "Roastbeef"],
		"account": ["Account:", "frankfurter"], 
		"server": ["Server:", "Barren Sky"],
		"guild": ["Guild:", "Tuna"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2012-11-20"],
		"charClass": ["Class:", "Defiler"],
		"sex": ["Sex:", "Female"],
		"level": ["Level:", "25"],
		"aa": ["AA\'s:", "120"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Love's food."]
	},	
	"character16": {
		"cName": ["Name:", "Torch"],
		"account": ["Account:", "ottowa"], 
		"server": ["Server:", "Guk"],
		"guild": ["Guild:", "Toadstool Harpies"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2010-10-10"],
		"charClass": ["Class:", "Wizard"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "89"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Lousy Wizard."]
	},	
	"character17": {
		"cName": ["Name:", "Deadwake"],
		"account": ["Account:", "sethjones2000"], 
		"server": ["Server:", "Everfrost"],
		"guild": ["Guild:", ""],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2013-02-20"],
		"charClass": ["Class:", "Necromancer"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "92"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Betrayed from Conj."]
	},	
	"character18": {
		"cName": ["Name:", "Scrubbinbubbles"],
		"account": ["Account:", "dj911turbo"], 
		"server": ["Server:", "Oasis"],
		"guild": ["Guild:", "One Man Army"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2010-12-20"],
		"charClass": ["Class:", "Mystic"],
		"sex": ["Sex:", "Female"],
		"level": ["Level:", "1"],
		"aa": ["AA\'s:", "0"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Oxidaxius Camp Spot."]
	},	
	"character19": {
		"cName": ["Name:", "Lentire"],
		"account": ["Account:", "lennylenlen"], 
		"server": ["Server:", "Freeport"],
		"guild": ["Guild:", "Forces of Evil"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2007-06-14"],
		"charClass": ["Class:", "Bruiser"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "95"],
		"aa": ["AA\'s:", "300"],
		"enervated": ["Enervated:", "Yes"],
		"harrows": ["Harrows:", "Yes"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Stinkin Bruiser!"]
	},	
	"character20": {
		"cName": ["Name:", "Venom"],
		"account": ["Account:", "comicon"], 
		"server": ["Server:", "Unrest"],
		"guild": ["Guild:", "Evil Villians"],
		"today": ["Today\'s Date:", "2013-05-20"],
		"creation": ["Creation Date:", "2004-09-20"],
		"charClass": ["Class:", "Beastlord"],
		"sex": ["Sex:", "Male"],
		"level": ["Level:", "77"],
		"aa": ["AA\'s:", "277"],
		"enervated": ["Enervated:", "No"],
		"harrows": ["Harrows:", "No"],
		"skyshrine": ["Skyshrine:", "No"],
		"bio": ["Bio:", "Spider-Man's nemesis."]
	}
}